language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
  dist: xenial
before_install:
- pip install poetry
install:
- poetry install -v
- pip install tox-travis
script:
- tox
- poetry build
# Extract the setup.py file
- tar -xf  dist/*.gz  && mv */setup.py .
deploy:
  provider: pypi
  user: jaimebuelta
  password:
    secure: jNRvdQ9zgAfFZP2bZdHk5S+s6OKKxrNKh1z9bx0EK0xjZlnYUVkW+aCr18DbgjHVfM4T3hLKRsoYIMRwQrY82wjdkycSXPX4us55plto0tYAqiODcTN2ZO2xuKf6tbh/IK4gaU9LnKtf8l9AVq0G4dlsYLsZNlPFaJzc4NBWTmKt0Jp91JFcAC2oCO7ofmqee/+nx4gOkxxcld9KQwWQ2rWDbduo6qFxedl4PGEgUx9M9dnqyy55j2Hzpkuycaom2pw4DZ89dt4c+NILoGkiB5StUpO3m0Wk77ossBdeR7tOlhfgihMUD61CZ8EY7Y6osZWi12+iGeeaqdB4vqNr+PmtqCElhinEtpOE2HhggNENToXQ7TjvGGIZz1ryaYRhE81K8zfJvP+WP5C/XGa5VGvV7PiCMVaz+BwqsBOoIYYbU82K0W3ltzn05lAqvwpzIQsWoxuXbzoja2Lyp01v1on2FgUScPWwDhQnKSK4JPpK4ra7C52wSiyJVxJJ9Iw2om/HXY2fu9qCt2VyagRNPzfy278XwJ6Q0wnstrn5KpndBmNeid0ajFRPybAIj69svKpvM0VbC5lmBuITJrwyNUMTrmoukE096f3C0SRdYgpMVnq/1VaPYfc1ZPovfCqatWc0CqUgjzOALPdimNRBWzC3U7h3SryDYtCvH9Z9Qz0=
  skip_existing: true
  skip_cleanup: true
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION == 3.7
