language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
matrix:
  include:
    # We need a newer Ubuntu than default for Python 3.7
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
install: 
  - pip install tox-travis
script: tox
